### ISSUE TITLE
After upgrade to v9.2.0 bump.config.ts not work

### ISSUE THREAD

**Issue by yunsii** [antfu/bumpp#13] opened 2023-08-26 09:25 UTC
### Describe the bug

After upgrade to v9.2.0 bump.config.ts not work, but with v9.1.0 it works.

### Reproduction

https://github.com/yunsii/unplugin-polish-tagged-templates

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 11.55 GB / 15.52 GB
    Container: Yes
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    pnpm: 8.6.9 - ~/.local/share/pnpm/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NamesMT** [comment] 2023-08-28 12:49
+1
![image](https://github.com/antfu/bumpp/assets/23612546/fd0a879d-8aaa-4535-98f5-c25116cfeea3)

**Comment by mattjin** [comment] 2023-10-12 10:53
+1

**Comment by chrisspiegl** [comment] 2023-10-18 10:49
I hope this get's resolved sometime.

**Comment by chrisspiegl** [comment] 2023-10-18 16:38
Duplicate of #6

**Closed** 2024-03-04 18:14 UTC
